<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sal_Alienware" failures="1" tests="2" name="Test(failed)" time="26.861" errors="0" timestamp="2022-08-22T12:19:04 EDT">
  <testcase classname="com.naveenautomations.Tests.OrderConfirmationPageTest" name="OrderConfirmationTest" time="1.926">
    <skipped/>
  </testcase> <!-- OrderConfirmationTest -->
  <testcase classname="com.naveenautomations.Tests.OrderConfirmationPageTest" name="OrderConfirmationTest" time="2.038">
    <failure type="java.lang.AssertionError" message="Order not confirmed expected [Your order has been successfullyprocessed!] but found [Your order has been successfully processed!]">
      <![CDATA[java.lang.AssertionError: Order not confirmed expected [Your order has been successfullyprocessed!] but found [Your order has been successfully processed!]
at com.naveenautomations.Tests.OrderConfirmationPageTest.OrderConfirmationTest(OrderConfirmationPageTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- OrderConfirmationTest -->
</testsuite> <!-- Test(failed) -->
